const data = [
  {
    id: 1,
    date: '12 han 2021',
    planType: 'ITR',
    planId: ' (IT)',
    states: 'complete',
    paymentState: 'paid',
    amount: '6000',
    name: 'syed',
    addOnTotal: 300,
    discount: 0,
    price: '8522',
    subRows: [
      {
        client: 'new',
        phone: '8050318651',
        email: 'syed hmail.com',
        orderId: '45454545454',
        addOns: ['hello', 'hello', 'hello'],
      },
    ],
  },
  {
    id: 2,
    date: '12 han 2021',
    planType: 'ITR',
    planId: ' (IT)',
    states: 'complete',
    paymentState: 'paid',
    amount: '6000',
    name: 'syed',
    addOnTotal: 300,
    discount: 0,
    price: '8522',
    subRows: [
      {
        client: 'new',
        phone: '8050318651',
        email: 'syed hmail.com',
        orderId: '45454545454',
        addOns: ['hello', 'hello', 'hello'],
      },
    ],
  },
  {
    id: 3,
    date: '12 han 2021',
    planType: 'ITR',
    planId: ' (IT)',
    states: 'complete',
    paymentState: 'paid',
    amount: '6000',
    name: 'syed',
    addOnTotal: 300,
    discount: 0,
    price: '8522',
    subRows: [
      {
        client: 'new',
        phone: '8050318651',
        email: 'syed hmail.com',
        orderId: '45454545454',
        addOns: ['hello', 'hello', 'hello'],
      },
    ],
  },
  {
    id: 4,
    date: '12 han 2021',
    planType: 'ITR',
    planId: ' (IT)',
    states: 'complete',
    paymentState: 'paid',
    amount: '6000',
    name: 'syed',
    addOnTotal: 300,
    discount: 0,
    price: '8522',
    subRows: [
      {
        client: 'new',
        phone: '8050318651',
        email: 'syed hmail.com',
        orderId: '45454545454',
        addOns: ['hello', 'hello', 'hello'],
      },
    ],
  },
  {
    id: 5,
    date: '12 han 2021',
    planType: 'ITR',
    planId: ' (IT)',
    states: 'complete',
    paymentState: 'paid',
    amount: '6000',
    name: 'syed',
    addOnTotal: 300,
    discount: 0,
    price: '8522',
    subRows: [
      {
        client: 'new',
        phone: '8050318651',
        email: 'syed hmail.com',
        orderId: '45454545454',
        addOns: ['hello', 'hello', 'hello'],
      },
    ],
  },
  {
    id: 6,
    date: '12 han 2021',
    planType: 'ITR',
    planId: ' (IT)',
    states: 'complete',
    paymentState: 'paid',
    amount: '6000',
    name: 'syed',
    addOnTotal: 300,
    discount: 0,
    price: '8522',
    subRows: [
      {
        client: 'new',
        phone: '8050318651',
        email: 'syed hmail.com',
        orderId: '45454545454',
        addOns: ['hello', 'hello', 'hello'],
      },
    ],
  },
];

export default data;
